<?php

/* This file is generated by the SQLicious Generator. www.sqlicious.com */

class ZipcodesDaoObject extends DataAccessObject
{
	function __construct($row = null)
	{
		parent::__construct($row);
	}

	function ZipcodesDaoObject($row = null)
	{
		self::__construct($row);
	}

	function getDatabaseName()
	{
		return 'sqlicious_test';
	}

	function getTableName()
	{
		return 'zipcodes';
	}

	function getIdField()
	{
		return 'zipcode_id';
	}

	static function getFactory()
	{
		return new ZipcodesDaoFactory();
	}
	
	final function setZipcodeId($val) { $this->setFieldValue('zipcode_id',$val); }
	final function getZipcodeId(){ return $this->getFieldValue('zipcode_id'); }
	
	final function setZipcode($val) { $this->setFieldValue('zipcode',$val); }
	final function getZipcode(){ return $this->getFieldValue('zipcode'); }
	
	final function setState($val) { $this->setFieldValue('state',$val); }
	final function getState(){ return $this->getFieldValue('state'); }
	
	final function setLongitude($val) { $this->setFieldValue('longitude',$val); }
	final function getLongitude(){ return $this->getFieldValue('longitude'); }
	
	final function setLatitude($val) { $this->setFieldValue('latitude',$val); }
	final function getLatitude(){ return $this->getFieldValue('latitude'); }
	
	final function setCity($val) { $this->setFieldValue('city',$val); }
	final function getCity(){ return $this->getFieldValue('city'); }
	
	final function setStateName($val) { $this->setFieldValue('state_name',$val); }
	final function getStateName(){ return $this->getFieldValue('state_name'); }
	
	function getDefaultRow()
	{
		return array('zipcode_id' => null, 'zipcode' => null, 'state' => null, 'longitude' => null, 'latitude' => null, 'city' => null, 'state_name' => null);
	}

}


class ZipcodesDaoFactory extends DataAccessObjectFactory
{
	function __construct()
	{
		parent::__construct();
	}

	function ZipcodesDaoFactory()
	{
		self::__construct();
	}

	function getDatabaseName()
	{
		return 'sqlicious_test';
	}

	function getTableName()
	{
		return 'zipcodes';
	}

	function getIdField()
	{
		return 'zipcode_id';
	}

	function loadDataObject($row)
	{
		return new ZipcodesDaoObject($row);
	}

	function getFields()
	{
		return array('zipcode_id', 'zipcode', 'state', 'longitude', 'latitude', 'city', 'state_name');
	}
	

}

?>